### ISSUE TITLE
Cannot find module '@microsoft/fetch-event-source' 

### ISSUE THREAD

**Issue by xpluscal** [tncrazvan/sveltekit-sse#14]
Using a fresh install I get the following error:

```
Error when evaluating SSR module /src/routes/+page.svelte: failed to import "/node_modules/sveltekit-sse/dist/index.js"
|- Error: Cannot find module '@microsoft/fetch-event-source' imported
```

Resolving the missing import fixes it, but thought this might be useful to prevent.

**Comment by tncrazvan** [comment]
Hi @xpluscal ,
thank you for the issue, it should be fixed now with version `0.4.14`.
Can you confirm?

**Comment by anatoliy-t7** [comment]
I got this error too on a new project
```js
 [ERROR] Could not resolve "@microsoft/fetch-event-source"

    node_modules/sveltekit-sse/dist/consume.js:4:7:
      4 │ } from '@microsoft/fetch-event-source'
 ```
 Tested with and without SSR
 #### Use:
- sveltekit-sse: 0.13.11
- svelteKit: 2.15.1
- svelte: 5.16.0
- npm: 10.8.2
- node: 20.18.1

**Comment by KCErb** [comment]
I just had the same issue on a fresh install of sveltekit-sse@^0.13.12

**Comment by razshare** [comment]
Hello @KCErb , I just created a project from scratch with svelte's cli and everything works fine on my end.

Could you, or anyone else experiencing the issue, please create e reproduction repository?
It's pretty difficult to understand what's going without an isolated reproduction.

**Comment by KCErb** [comment]
I just reproduced on node v23.5.0
```
npx sv create my-app                  
Need to install the following packages:
sv@0.6.16
Ok to proceed? (y) y
```

Then I gave the CLI the following:

```

┌  Welcome to the Svelte CLI! (v0.6.16)
│
◇  Which template would you like?
│  SvelteKit minimal
│
◇  Add type checking with Typescript?
│  Yes, using Typescript syntax
│
◆  Project created
│
◇  What would you like to add to your project? (use arrow keys / space bar)
│  none
│
◇  Which package manager do you want to install dependencies with?
│  yarn
│
◆  Successfully installed dependencies
```

Then I started I add sveltekit-sse with yarn

```
cd my-app 
yarn add sveltekit-sse
yarn add v1.22.22
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > sveltekit-sse@0.13.12" has unmet peer dependency "@microsoft/fetch-event-source@^2.0.1".
warning Workspaces can only be enabled in private projects.
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
warning Workspaces can only be enabled in private projects.
success Saved 1 new dependency.
info Direct dependencies
└─ sveltekit-sse@0.13.12
info All dependencies
└─ sveltekit-sse@0.13.12
$ svelte-kit sync || echo ''
✨  Done in 1.00s.
```

Then I started with no errors
```
➜  my-app yarn run dev --open       
yarn run v1.22.22
$ vite dev --open
Forced re-optimization of dependencies
Port 5173 is in use, trying another one...

  VITE v6.0.11  ready in 391 ms```
```

Then I added an import statement to src/routes/+page.svelte

```
<script>
    import { source } from 'sveltekit-sse'
</script>
<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://svelte.dev/docs/kit">svelte.dev/docs/kit</a> to read the documentation</p>
```

and boom 💥 

```
✘ [ERROR] Could not resolve "@microsoft/fetch-event-source"

    node_modules/sveltekit-sse/dist/consume.js:4:7:
      4 │ } from '@microsoft/fetch-event-source'
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@microsoft/fetch-event-source" as external to exclude it from the bundle,
  which will remove this error and leave the unresolved path in the bundle.

12:28:16 PM [vite] (client) error while updating dependencies:
Error: Build failed with 1 error:
node_modules/sveltekit-sse/dist/consume.js:4:7: ERROR: Could not resolve "@microsoft/fetch-event-source"
    at failureErrorWithLog (/Users/kcerb/tmp/my-app/node_modules/esbuild/lib/main.js:1476:15)
    at /Users/kcerb/tmp/my-app/node_modules/esbuild/lib/main.js:945:25
    at /Users/kcerb/tmp/my-app/node_modules/esbuild/lib/main.js:1354:9
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```
